name: recogbase
version: 1.3
date: 2018-09-16
description: |
    Withdrawn package, use 'recog' instead

authors:
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Ákos Seress

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

needed-pkgs:
    - name: "recog"
      version: ">= 1.3"
      url: "https://gap-packages.github.io/recog"

www: https://gap-packages.github.io/recogbase
readme: README.md
packageinfo: https://gap-packages.github.io/recogbase/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/recogbase/releases/download/v1.3/recogbase-1.3.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/recogbase/releases/download/v1.3/recogbase-1.3.tar.bz2

abstract: |
    <b>Warning:</b> This package has been withdrawn. Please use the <span class="pkgname">recog</span> package instead.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
